### ISSUE TITLE
New plan to bust out of iframe.

### ISSUE THREAD

**Issue by AhoyLemon** [AhoyLemon/idiots.win#15]
The way that I have implemented shitty websites iframing in Idiots win is to try to remove it from the iframe.

`_actions.js`, line 60

However, browsers are preventing this from working.

**SO**, find another way to fuck with those sites.

**Comment by wopian** [comment]
You can block the site from being embedded by other websites using two headers.

```
X-Frame-Options: DENY
Content-Security-Policy: ...rest of CSP options; frame-ancestors 'none';
```

https://securityheaders.com/?q=https%3A%2F%2Fidiots.win%2F

**Comment by AhoyLemon** [comment]
Good thought, @wopian - but there's two problems with that.

1. idiots.win is Github pages. I'm not sure if that's possible to edit headers in this case.
2. If I could, actually fully disabling the iframe is still subotptimal. These arcade sites are saying "One of our games is idiots.win", and I'd like the user to know, "Well, here's idiots win, but it's not owned by this arcade site." Blocking the thing entirely just shuts that conversation down.
